### ISSUE TITLE
Add support for git describe --match

### ISSUE THREAD

**Issue by ghost** [code54/buildversion-plugin#7]
Isn't --match or --exact-match the --first-parent you are referring to?

**Comment by dobladez** [comment]
Hmm I don't think so...  unless I'm missing something.

The plugin has logic similar to what `--match` does in order to avoid leaking "private" tags (it only looks for tags that start with `v`).

Regarding `git describe --exact-match`, I don't see how it would help: it only works if the repo has a tag pointing to HEAD, which is only a special case (the easiest one actually, since there's no need to walk the history at all).

Thanks

**Comment by carlos** [comment]
Closing this issue since we didn't get any feedback for many years.
